name: E2E Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # exécution chaque nuit à 3h du matin

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run start & npx wait-on http://localhost:3000
      - run: npm run e2e
